// app/layout.tsx

import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable : "--font-sans"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable )}>{children}</body>
    </html> 
  );
};

export default Layout;
